<?php

namespace Hyvr\Rocket\Commands;

use Hyvr\Rocket\Helpers\ConfigHelper;
use Hyvr\Rocket\Helpers\TerminalHelper;
use Illuminate\Console\Command;
use Illuminate\Support\Facades\File;

class RunCommand extends Command
{
    protected $signature = 'rocket:run';
    protected $description = 'Run the static build generated by Rocket';

    public function handle(){
        TerminalHelper::printHeader($this);

        ConfigHelper::init($this);

        $build_path = base_path('build');
        $host = config('rocket.server.host', '127.0.0.1');
        $port = config('rocket.server.port', '4000');
        $command = 'php -S '.$host.':'.$port.' -t build';

        $this->line('<fg=yellow>⚡️ Starting the build server.</>');
        $this->newLine();

        if(!File::isDirectory($build_path)){
            $this->error('Error: Build folder does not exists in this path: '.$build_path);
        }
        else{
            $this->line('<fg=yellow>🍕 Server server is started, Go to the link (<href=http://'.$host.':'.$port.'>http://'.$host.':'.$port.'</>) to view the site.</>');
            $this->newLine();

            passthru($command);
        }
    }
}